import type { Lead } from './page'

// Demo fixture data — gebruikt in de publieke demo om echte leads te beschermen
export const DEMO_LEADS: Lead[] = [
  {
    id: 'demo-1',
    naam: 'Lars van den Berg',
    email: 'lars@groeibedrijf.nl',
    bedrijf: 'Groeibedrijf BV',
    telefoon: '+31 6 12345678',
    bericht: 'Wij zijn op zoek naar een manier om onze leads automatisch op te volgen. We krijgen 40-50 inbound aanvragen per maand maar missen er te veel door trage opvolging.',
    bron: 'website',
    status: 'nieuw',
    ai_score: 'hoog',
    ai_sector: 'SaaS',
    ai_samenvatting: 'MKB-directeur met concrete leadproblemen, budget aanwezig, beslist snel. Hoge urgentie.',
    ai_prioriteit: 92,
    follow_up_verstuurd: false,
    aangemaakt_op: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    crm_gesynchroniseerd: false,
    crm_type: null,
    verrijking: { bedrijfsnaam: 'Groeibedrijf BV', sector: 'SaaS', grootte: '11-50', land: 'NL', linkedin: null },
  },
  {
    id: 'demo-2',
    naam: 'Mieke Jansen',
    email: 'mieke@mktconsult.nl',
    bedrijf: 'MKT Consult',
    telefoon: null,
    bericht: 'Ik ben freelance marketeer en zoek een tool om mijn klanten sneller op te volgen na een demo. Wat zijn jullie tarieven?',
    bron: 'LinkedIn',
    status: 'follow_up_verstuurd',
    ai_score: 'middel',
    ai_sector: 'Marketing',
    ai_samenvatting: 'Freelancer met interesse maar budget onduidelijk. Mogelijk doorgroeipotentieel als ze meerdere klanten bedient.',
    ai_prioriteit: 67,
    follow_up_verstuurd: true,
    aangemaakt_op: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    crm_gesynchroniseerd: true,
    crm_type: 'hubspot',
    verrijking: null,
  },
  {
    id: 'demo-3',
    naam: 'Thomas Akkerman',
    email: 'thomas@akkermanadvies.nl',
    bedrijf: 'Akkerman Advies',
    telefoon: '+31 20 1234567',
    bericht: 'Wij zijn een adviesbureau met 15 consultants. Lead management is momenteel een grote pijn. Stuur mij meer informatie.',
    bron: 'website',
    status: 'uitgenodigd',
    ai_score: 'hoog',
    ai_sector: 'Consulting',
    ai_samenvatting: 'Adviesbureau met schaalgrootte en pijn. Hoge sluitkans. Wil informatie voor team-beslissing.',
    ai_prioriteit: 88,
    follow_up_verstuurd: true,
    aangemaakt_op: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    crm_gesynchroniseerd: false,
    crm_type: null,
    verrijking: { bedrijfsnaam: 'Akkerman Advies', sector: 'Consulting', grootte: '11-50', land: 'NL', linkedin: 'https://linkedin.com/company/akkerman-advies' },
  },
  {
    id: 'demo-4',
    naam: 'Sophie de Groot',
    email: 'sophie@webshopnl.nl',
    bedrijf: 'WebshopNL',
    telefoon: null,
    bericht: 'Hallo, kunnen jullie ook helpen bij e-commerce leads? We verkopen B2B producten en willen de opvolging verbeteren.',
    bron: 'Google Ads',
    status: 'nieuw',
    ai_score: 'middel',
    ai_sector: 'E-commerce',
    ai_samenvatting: 'E-commerce speler met B2B focus, onduidelijk budget. Potentieel maar nog vroeg in oriëntatiefase.',
    ai_prioriteit: 58,
    follow_up_verstuurd: false,
    aangemaakt_op: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    crm_gesynchroniseerd: false,
    crm_type: null,
    verrijking: null,
  },
  {
    id: 'demo-5',
    naam: 'Kevin Smits',
    email: 'kevin@ict-pro.nl',
    bedrijf: 'ICT Pro Solutions',
    telefoon: '+31 6 87654321',
    bericht: 'We zijn een IT-bedrijf en willen onze sales pipeline automatiseren. Budget: €500-1000 per maand. Wanneer kunnen we spreken?',
    bron: 'website',
    status: 'behandeld',
    ai_score: 'hoog',
    ai_sector: 'IT',
    ai_samenvatting: 'IT-bedrijf met concreet budget en hoge koopbereidheid. Klaar voor demo.',
    ai_prioriteit: 95,
    follow_up_verstuurd: true,
    aangemaakt_op: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    crm_gesynchroniseerd: true,
    crm_type: 'pipedrive',
    verrijking: { bedrijfsnaam: 'ICT Pro Solutions', sector: 'IT', grootte: '51-200', land: 'NL', linkedin: null },
  },
  {
    id: 'demo-6',
    naam: 'Emma Willems',
    email: 'emma@recruitmentsucces.nl',
    bedrijf: 'Recruitment Succes',
    telefoon: null,
    bericht: 'Wij zijn een recruitmentbureau en hebben veel inbound kandidaten en opdrachtgevers. Is Runvex ook geschikt voor recruitment?',
    bron: 'referral',
    status: 'nieuw',
    ai_score: 'laag',
    ai_sector: 'HR & Recruitment',
    ai_samenvatting: 'Recruitment niche — product fit onduidelijk. Lage urgentie, oriënterend gesprek.',
    ai_prioriteit: 32,
    follow_up_verstuurd: false,
    aangemaakt_op: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    crm_gesynchroniseerd: false,
    crm_type: null,
    verrijking: null,
  },
  {
    id: 'demo-7',
    naam: 'Pieter Hofman',
    email: 'pieter@groeimkb.nl',
    bedrijf: 'Groei MKB',
    telefoon: '+31 6 11223344',
    bericht: 'Ik help MKB-bedrijven groeien als consultant. Mijn klanten hebben allemaal last van slechte lead-opvolging. Kunnen we een partnerschap bespreken?',
    bron: 'LinkedIn',
    status: 'nieuw',
    ai_score: 'hoog',
    ai_sector: 'Consulting',
    ai_samenvatting: 'Potentiële reseller/partner die meerdere klanten kan aandragen. Hoge lifetime value.',
    ai_prioriteit: 85,
    follow_up_verstuurd: false,
    aangemaakt_op: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    crm_gesynchroniseerd: false,
    crm_type: null,
    verrijking: { bedrijfsnaam: 'Groei MKB', sector: 'Consulting', grootte: '1-10', land: 'NL', linkedin: null },
  },
]
